### ISSUE TITLE
Umnet dependancies

### ISSUE THREAD

**Issue by martinfrances107** [carver/docker-ircd#3]
This project looks very useful ...

So I am just going to get the project up and running again

I am just posting early, before I bug hunt - I think this just needs a little TLC

here the the response to 

docker build .

Sending build context to Docker daemon 88.06 kB
Step 1/12 : FROM ubuntu
latest: Pulling from library/ubuntu
d54efb8db41d: Pull complete 
f8b845f45a87: Pull complete 
e8db7bf7c39f: Pull complete 
9654c40e9079: Pull complete 
6d9ef359eaaa: Pull complete 
Digest: sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535
Status: Downloaded newer image for ubuntu:latest
 ---> 0ef2e08ed3fa
Step 2/12 : MAINTAINER Jason Carver <ut96caarrs@snkmail.com>
 ---> Running in 020901d3f17b
 ---> 66d690675e3c
Removing intermediate container 020901d3f17b
Step 3/12 : RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
 ---> Running in c75ed37fca45
 ---> 04ed3fcd9b3a
Removing intermediate container c75ed37fca45
Step 4/12 : RUN apt-get update
 ---> Running in b778a1448854
Ign:1 http://archive.ubuntu.com/ubuntu precise InRelease
Get:2 http://archive.ubuntu.com/ubuntu precise Release [49.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu precise Release.gpg [198 B]
Get:4 http://archive.ubuntu.com/ubuntu precise/main amd64 Packages [1640 kB]
Get:5 http://archive.ubuntu.com/ubuntu precise/universe amd64 Packages [6167 kB]
Fetched 7857 kB in 9s (868 kB/s)
Reading package lists...
W: http://archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
 ---> c0b16b303f07
Removing intermediate container b778a1448854
Step 5/12 : RUN apt-get install -y sysklogd ngircd
 ---> Running in d1d0f01ac32a
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ngircd : Depends: perl but it is not going to be installed
 sysklogd : Depends: klogd or
                     linux-kernel-log-daemon
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y sysklogd ngircd' returned a non-zero code: 100

**Comment by martinfrances107** [comment]
The commit above fixes the issue for me 

sysklogd has been replaced by rsyslog 

I hope this is useful.

**Comment by carver** [comment]
Thanks! I believe #2 fixed this as well, it was just merged in. Please reopen if you continue to have issues.
